### ISSUE TITLE
Ideas for enforcing character class rules

### ISSUE THREAD

**Issue by gmalouf** [gmalouf/averruncus#2]
@beezee I'm debating a bit how best to implement the baseline character class rules (with regexes).  One option is to create many small regex-based rules and enforce each piece as it's own rule.

`(?=.*[A-Z])`
`(?=.*[a-z])`
`(?=.*[0-9])`
`(?=.*[\W])`
`^\S*$`

Another is to put them together:

`^(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9])(?=.*[\W])\S*$`

The above enforces that a string contains at least 1 upper char, lower char, number and special char.  Additionally, it disallows whitespace characters from being present anywhere in the string.

While the first option is definitely the most flexible, it seems a bit wasteful to match many different regexes against a string...maybe the best option is to include a bunch of individual rules in addition to some that are combined together out-of-the-box?

**Comment by beezee** [comment]
My regex-fu is lagging on this one, does the all-in-one approach imply order? 

If not it seems like it could be a perf gain, though arguably immaterial. One thing I've definitely learned is to define the regex as a val on an object to prevent recompilation, but I'm less aware of the cost of doing a comparison.

If the perf q is meaningful, seems like one rule with all of them (the combined regex) plus the individual ones might be the easy way to gain flexibility, but a more interesting path would be something where you could compose regex based rules that built up to a single match. That path definitely carries a decent risk of bike shedding though, fun as it might be to go down.

One side note on composable regex rules, it also probably requires a bit of a re-think on rule definition that leads to an even purer functional approach.

**Comment by gmalouf** [comment]
The all-in-one approach doesn't apply an order, it just enforces all the rules in a single regex pattern.  

Thinking about this more, I don't think we should be too worried about the performance of checking against one vs multiple regexes at this point.  It's easier to give a meaningful, specific error message back to the caller if we keep each regex pattern as it's own rule.  

Given the individual approach, I don't think a composer is needed yet.  Someone can always implement their own rule if they really want to as well.

**Comment by beezee** [comment]
Good point and practical thinking.

:+1: 

Also just brushed up on lookahead, thanks for prompting.

**Comment by beezee** [comment]
Addressed by #4
